name: TandemArch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37618
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: TandemArch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e2dd'
    - '#df844a'
    - '#a6cad7'
    - '#623723'
    - '#4f969c'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
